
export var tableData=[
    {
      "id":"1",
      "sys_Date":null,
      "lastModifiedDate":null,
      "markAsDeleted":false,
      "gallery_name_id":"2",
      "gallery_name":"彩虹西路(将军岭路~鸡鸣山路)",
      "work_name":"预警派单",
      "work_detailed":"预警派单详情",
      "work_line":'预定路线',
      "work_line_id":null,
      "work_status":"启动",
      "work_user":"王强",
      "work_time":'每周一',
      "work_type":'养护',
      "startDate":"2018-11-03 12:45:00",
      "endDate":"2018-11-03 23:30:00",
    },
  {
    "id":"2",
    "sys_Date":null,
    "lastModifiedDate":null,
    "markAsDeleted":false,
    "gallery_name_id":"2",
    "gallery_name":"彩虹西路(将军岭路~鸡鸣山路)",
    "work_name":"预警派单",
    "work_detailed":"预警派单详情",
    "work_line":'预定路线',
    "work_line_id":null,
    "work_status":"启动",
    "work_user":"王强",
    "work_time":'每周一',
    "work_type":'巡检',
    "startDate":"2018-11-03 12:45:00",
    "endDate":"2018-11-03 23:30:00",
  }

]